/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cenfotec.calculadoraControl;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Evese
 */
public class CalculadoraPanel extends javax.swing.JPanel {

    String operador = "";
    boolean existePrimerNumero= false;
    boolean existeSegundoNumero = false;
    
    /**
     * Creates new form CalculadoraPanel
     */
    public CalculadoraPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButtonNueve = new javax.swing.JButton();
        JButtonSiete = new javax.swing.JButton();
        JButtonSeis = new javax.swing.JButton();
        JButtonCinco = new javax.swing.JButton();
        JButtonCuatro = new javax.swing.JButton();
        JButtonOcho = new javax.swing.JButton();
        JButtonCero = new javax.swing.JButton();
        JButtonTres = new javax.swing.JButton();
        JButtonUno = new javax.swing.JButton();
        JButtonSumar = new javax.swing.JButton();
        JButtonIgual = new javax.swing.JButton();
        JButtonDividir = new javax.swing.JButton();
        JButtonMultiplicar = new javax.swing.JButton();
        JButtonRestar = new javax.swing.JButton();
        JButtonClean = new javax.swing.JButton();
        JButtonDos = new javax.swing.JButton();
        labelTotal = new java.awt.Label();

        setBackground(new java.awt.Color(255, 204, 0));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CALCULADORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 100));

        JButtonNueve.setBackground(new java.awt.Color(255, 255, 255));
        JButtonNueve.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonNueve.setText("9");
        JButtonNueve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonNueveActionPerformed(evt);
            }
        });

        JButtonSiete.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonSiete.setText("7");
        JButtonSiete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSieteActionPerformed(evt);
            }
        });

        JButtonSeis.setBackground(new java.awt.Color(255, 255, 255));
        JButtonSeis.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonSeis.setText("6");
        JButtonSeis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSeisActionPerformed(evt);
            }
        });

        JButtonCinco.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonCinco.setText("5");
        JButtonCinco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCincoActionPerformed(evt);
            }
        });

        JButtonCuatro.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonCuatro.setText("4");
        JButtonCuatro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCuatroActionPerformed(evt);
            }
        });

        JButtonOcho.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonOcho.setText("8");
        JButtonOcho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonOchoActionPerformed(evt);
            }
        });

        JButtonCero.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonCero.setText("0");
        JButtonCero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCeroActionPerformed(evt);
            }
        });

        JButtonTres.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonTres.setText("3");
        JButtonTres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonTresActionPerformed(evt);
            }
        });

        JButtonUno.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonUno.setText("1");
        JButtonUno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonUnoActionPerformed(evt);
            }
        });

        JButtonSumar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JButtonSumar.setText("+");
        JButtonSumar.setToolTipText("");
        JButtonSumar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSumarActionPerformed(evt);
            }
        });

        JButtonIgual.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JButtonIgual.setText("=");
        JButtonIgual.setToolTipText("");
        JButtonIgual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonIgualActionPerformed(evt);
            }
        });

        JButtonDividir.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JButtonDividir.setText("÷");
        JButtonDividir.setToolTipText("");
        JButtonDividir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonDividirActionPerformed(evt);
            }
        });

        JButtonMultiplicar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JButtonMultiplicar.setText("x");
        JButtonMultiplicar.setToolTipText("");
        JButtonMultiplicar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonMultiplicarActionPerformed(evt);
            }
        });

        JButtonRestar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JButtonRestar.setText("-");
        JButtonRestar.setToolTipText("");
        JButtonRestar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRestarActionPerformed(evt);
            }
        });

        JButtonClean.setBackground(new java.awt.Color(255, 51, 0));
        JButtonClean.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        JButtonClean.setText("C");
        JButtonClean.setToolTipText("");
        JButtonClean.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCleanActionPerformed(evt);
            }
        });

        JButtonDos.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        JButtonDos.setText("2");
        JButtonDos.setToolTipText("");
        JButtonDos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JButtonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonDosActionPerformed(evt);
            }
        });

        labelTotal.setAlignment(java.awt.Label.RIGHT);
        labelTotal.setBackground(new java.awt.Color(255, 255, 255));
        labelTotal.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JButtonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JButtonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JButtonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(JButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(JButtonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JButtonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JButtonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JButtonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JButtonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(JButtonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JButtonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JButtonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JButtonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JButtonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonNueve)
                    .addComponent(JButtonOcho)
                    .addComponent(JButtonSiete)
                    .addComponent(JButtonClean))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonSeis)
                    .addComponent(JButtonCinco)
                    .addComponent(JButtonCuatro)
                    .addComponent(JButtonTres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonUno)
                    .addComponent(JButtonCero)
                    .addComponent(JButtonSumar)
                    .addComponent(JButtonDos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JButtonDividir)
                        .addComponent(JButtonMultiplicar)
                        .addComponent(JButtonRestar))
                    .addComponent(JButtonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void modificarExistenciaNumeros(){
        if(!this.existePrimerNumero){
            this.existePrimerNumero = true;
        }
        if(existeOperador()){
            this.existeSegundoNumero = true;
        }
    }
    private void JButtonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSieteActionPerformed
        this.labelTotal.setText(this.labelTotal.getText()+7);
        modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonSieteActionPerformed

    private void JButtonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSeisActionPerformed
        this.labelTotal.setText(this.labelTotal.getText()+6);
         modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonSeisActionPerformed

    private void JButtonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCincoActionPerformed
        this.labelTotal.setText(this.labelTotal.getText()+5);
         modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonCincoActionPerformed

    private void JButtonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCuatroActionPerformed
        this.labelTotal.setText(this.labelTotal.getText()+4);
         modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonCuatroActionPerformed

    private void JButtonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonOchoActionPerformed
        this.labelTotal.setText(this.labelTotal.getText()+8);
         modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonOchoActionPerformed

    private void JButtonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCeroActionPerformed
        this.labelTotal.setText(this.labelTotal.getText()+0);
         modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonCeroActionPerformed

    private void JButtonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonTresActionPerformed
        this.labelTotal.setText(this.labelTotal.getText()+3);
         modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonTresActionPerformed

    private void JButtonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonUnoActionPerformed
        this.labelTotal.setText(this.labelTotal.getText()+1);
         modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonUnoActionPerformed

    private void JButtonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSumarActionPerformed
       
         if(this.existePrimerNumero){
               if(!existeOperador()){
                this.labelTotal.setText(this.labelTotal.getText()+"+");
                this.operador = "+";
        }else{      
           mostrarMensaje("Ya existe un operador, botón inválido");
        } 
         }else{
              mostrarMensaje("Debe digitar un número primero");
         }     
   
    }//GEN-LAST:event_JButtonSumarActionPerformed

    private void JButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonIgualActionPerformed
        if(existeOperador() && existeSegundoNumero){
          String operacion = this.labelTotal.getText();
        int indexOperador = operacion.indexOf(this.operador);
        double num1 = Integer.parseInt(operacion.substring(0,indexOperador));
        double num2 = Integer.parseInt(operacion.substring(indexOperador+1));
        double total = 0;
        switch(this.operador){
            case "+":
                total = num1 + num2;
                break;
            case "-":
                total = num1 - num2;
                break;
            case "x":
                total = num1 * num2;
                break;
            default:
                total = num1 / num2;
                break;                
        };
        
        this.labelTotal.setText(Double.toString(total));
        this.existePrimerNumero = false;
        this.existeSegundoNumero = false;
        this.operador = "";
        JButtonCero.setEnabled(false);
        JButtonUno.setEnabled(false);
        JButtonDos.setEnabled(false);
        JButtonTres.setEnabled(false);
        JButtonCuatro.setEnabled(false);
        JButtonCinco.setEnabled(false);
        JButtonSeis.setEnabled(false);
        JButtonSiete.setEnabled(false);
        JButtonOcho.setEnabled(false);
        JButtonNueve.setEnabled(false);
        JButtonSumar.setEnabled(false);
        JButtonRestar.setEnabled(false);
        JButtonDividir.setEnabled(false);
        JButtonMultiplicar.setEnabled(false);
        JButtonIgual.setEnabled(false);
        }else{
            mostrarMensaje("No se puede realizar la operación, falta el operador o el segundo número");
        }        
      
    }//GEN-LAST:event_JButtonIgualActionPerformed

    private boolean existeOperador(){
        if(!this.operador.equals("")){
            return true;
        }
        return false;
    }
    
    private void mostrarMensaje(String msj){
     JOptionPane.showMessageDialog(this, msj);
    }
    private void JButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonDividirActionPerformed
       
        if(this.existePrimerNumero){
              if(!existeOperador()){
                this.labelTotal.setText(this.labelTotal.getText()+"÷");
                this.operador = "÷";
               }else{      
                  mostrarMensaje("Ya existe un operador, botón inválido");
        } 
        }else{
              mostrarMensaje("Debe digitar un número primero");
        }     
      
    
         
    }//GEN-LAST:event_JButtonDividirActionPerformed

    private void JButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonMultiplicarActionPerformed
        if(this.existePrimerNumero){
              if(!existeOperador()){
                this.labelTotal.setText(this.labelTotal.getText()+"x");
                this.operador = "x";
               }else{      
                  mostrarMensaje("Ya existe un operador, botón inválido");
        } 
        }else{
              mostrarMensaje("Debe digitar un número primero");
        }     
      
    }//GEN-LAST:event_JButtonMultiplicarActionPerformed

    private void JButtonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRestarActionPerformed
    
        if(this.existePrimerNumero){            
            if(!existeOperador()){
                this.labelTotal.setText(this.labelTotal.getText()+"-");
                this.operador = "-";
            }else{      
                  mostrarMensaje("Ya existe un operador, sólo se permite una operación por turno. Botón inválido");
            } 
        }else{
            mostrarMensaje("Debe digitar un número primero");
        }
    
    }//GEN-LAST:event_JButtonRestarActionPerformed

    private void JButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCleanActionPerformed
        this.operador = "";
        this.labelTotal.setText("");
        this.existePrimerNumero = false;
        this.existeSegundoNumero = true;
        JButtonCero.setEnabled(true);
        JButtonUno.setEnabled(true);
        JButtonDos.setEnabled(true);
        JButtonTres.setEnabled(true);
        JButtonCuatro.setEnabled(true);
        JButtonCinco.setEnabled(true);
        JButtonSeis.setEnabled(true);
        JButtonSiete.setEnabled(true);
        JButtonOcho.setEnabled(true);
        JButtonNueve.setEnabled(true);
        JButtonSumar.setEnabled(true);
        JButtonRestar.setEnabled(true);
        JButtonDividir.setEnabled(true);
        JButtonMultiplicar.setEnabled(true);
        JButtonIgual.setEnabled(true);
        
    }//GEN-LAST:event_JButtonCleanActionPerformed

    private void JButtonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonDosActionPerformed
        this.labelTotal.setText(this.labelTotal.getText()+2);
         modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonDosActionPerformed

    private void JButtonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonNueveActionPerformed
      this.labelTotal.setText(this.labelTotal.getText()+9);
       modificarExistenciaNumeros();
    }//GEN-LAST:event_JButtonNueveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCero;
    private javax.swing.JButton JButtonCinco;
    private javax.swing.JButton JButtonClean;
    private javax.swing.JButton JButtonCuatro;
    private javax.swing.JButton JButtonDividir;
    private javax.swing.JButton JButtonDos;
    private javax.swing.JButton JButtonIgual;
    private javax.swing.JButton JButtonMultiplicar;
    private javax.swing.JButton JButtonNueve;
    private javax.swing.JButton JButtonOcho;
    private javax.swing.JButton JButtonRestar;
    private javax.swing.JButton JButtonSeis;
    private javax.swing.JButton JButtonSiete;
    private javax.swing.JButton JButtonSumar;
    private javax.swing.JButton JButtonTres;
    private javax.swing.JButton JButtonUno;
    private java.awt.Label labelTotal;
    // End of variables declaration//GEN-END:variables
}
