/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mylineasapp;

/**
 *
 * @author Evese
 */
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.Shape;
import javax.swing.JFrame;
import javax.swing.JPanel;
public class Surface extends javax.swing.JPanel {

    /**
     * Creates new form Surface
     */
    private void doDrawing(Graphics g) {

        Graphics2D g2d = (Graphics2D) g;

//        g2d.drawLine(30, 30, 200, 30);
//        g2d.drawLine(200, 30, 30, 200);
//        g2d.drawLine(30, 200, 200, 200);
//        g2d.drawLine(200, 200, 30, 30);
       
        g2d.drawLine(40, 20, 40, 270);        
        g2d.drawLine(40, 270, 360, 270);
        g.setFont( new Font( "Serif", Font.ITALIC, 14 ));
        String titulo = "Cantidad de plantas por especie";
      
        g.drawString(titulo,(300/2)-(titulo.length()/2),10 );
        
        g2d.drawLine(30,270,40,270); //Cero
        g.drawString("0",10,270);
        g2d.drawLine(30,220,40,220); //Diez
         g.drawString("10",10,220);
        g2d.drawLine(30,170,40,170);//Veinte
         g.drawString("20",10,170);
        g2d.drawLine(30,120,40,120);//Treinta
         g.drawString("30",10,120);
        g2d.drawLine(30,70,40,70); //Cuarenta
         g.drawString("40",10,70);
        g2d.drawLine(30,20,40,20); //Cincuenta
         g.drawString("50",10,20);
         
        g.setColor(Color.GREEN);
        Rectangle rect = new Rectangle(60,20,20,250); 
        g.fillRect(60,20,20,250);
        g2d.draw(rect);
       
        
        g.setColor(Color.BLUE);
        Rectangle rect2 = new Rectangle(120,120,20,150);
         g.fillRect(120,120,20,150);
        g2d.draw(rect2);
       
        
          g.setColor(Color.RED);
        Rectangle rect3 = new Rectangle(180,220,20,50);
         g.fillRect(180,220,20,50);
         g2d.draw(rect3);
         
         g.setColor(Color.yellow);
        Rectangle rect4 = new Rectangle(240,245,20,25);
         g.fillRect(240,245,20,25);
         g2d.draw(rect4);
         
         g.setColor(Color.black);
    
          g.drawString("Verde = cactus",10,300 );
                
          g.drawString("Azul = sedum",10,320 );
                   
          g.drawString("Rojo = echeverría",10,340 );
                   
          g.drawString("Amarillo = kalanchoe",10,360 );
    } 
    

    @Override
    public void paintComponent(Graphics g) {

        super.paintComponent(g);
       
        doDrawing(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
